#!/usr/bin/with-contenv bash

echo "Starting Plexdrive"

exec s6-setuidgid plex \
      /bin/sh -c \
        "/usr/local/bin/plexdrive mount -v 2 -c ${HOME}/.plexdrive --cache-file=${HOME}/.plexdrive/cache.bolt -o allow_other ${PLEXDRIVE_MOUNT_POINT}"
